### ISSUE TITLE
chat isn't showing player colors

### ISSUE THREAD

**Issue by misterff1** [alecxvs/UTChat#15]
Instead of the assigned player color, a nearly white color is shown for the playernames in chat.

**Comment by alecxvs** [comment]
Can you link to an image of this?

**Comment by misterff1** [comment]
Currently on my phone. You can see for yourself if you join jcmp.gaveroid.com or lookup Gaveroid's Scavenger Hunt server in the serverlist. You'll see that the colors are different than the LocalPlayer:GetColor ones you see in the F6 menu. In the chat almost every player has a color that is almost white

**Comment by misterff1** [comment]
Online 111 in utchat.lua, I see that the color is defined. However, you use 150, 150, 150 as a base and add a random amount to each of them. That makes it a lot less lively than default chat. Maybe you could use LocalPlayer:GetColor() instead or start from a lower number (or make an option so people can select whether they want the assigned or a random color)

**Comment by alecxvs** [comment]
Unless it was changed, GetColor doesn't return the default colors assigned to chat names, it only returns one color for all players. The code to calculate that color is known, though, and I use some variation of it.

As for the lightness, that's intended due to contrast. Because the text is also slightly transparent, has a thinner font, and has less of a shadow, it needs to stand out better against the environment. I can see about tweaking it if it would help because I've never actually seen it used in an active server with a variety of colors.

If the colors are different from what they are in a gamemode or something that defines its own color scheme, there isn't much I can do about that unless the gamemode can set what GetColor returns or sets some "standard" player value. I can override the generated color if that is set, then. If you know which is the case, let me know and I'll see about adding that.

**Comment by misterff1** [comment]
Scripts always tend to use GetColor for player colors, but as this is intended, I think it is best to leave it to server owners to change it then.
